#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format
if test "$(git rev-parse --abbrev-ref HEAD)" = "main" ; then npm run build ; else npm run build:dev ; fi
git add tsconfig.tsbuildinfo
