name: CD

on:
  push:
    branches:
    - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
         node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: ESLint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Make dotenv file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          file_name: .env.development

          envkey_VITE_EXAMPLE_KEY: ${{ secrets.VITE_EXAMPLE_KEY }}

          envkey_VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          envkey_VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          envkey_VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          envkey_VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          envkey_VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          envkey_VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          envkey_VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}

      - name: Build
        run: yarn build:dev

      - name: Auth in GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: deploy
        name: Deploy to GAE
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.dev.yaml
